[workspace]
authors = ["Sam Perry <sper@skl.vc>"]
channels = ["conda-forge",
"https://prefix.dev/robostack"]
name = "ros1"
platforms = ["linux-64"]
version = "0.1.0"

[activation]
scripts = ["devel/setup.bash"]

[tasks]

[dependencies]
#ros-noetic-ros = ">=1.15.8,<2"
#ros-noetic-desktop = ">=1.5.0,<2"
#ros-noetic-rosgraph-msgs = ">=1.11.3,<2"
#ros-noetic-controller-interface = ">=0.19.5,<0.20"
#ros-noetic-rosgraph = ">=1.15.14,<2"
#ros-noetic-hardware-interface = ">=0.19.5,<0.20"
#ros-noetic-desktop-full = ">=1.5.0,<2"
#catkin_tools = ">=0.9.4,<0.10"
python = "3.8.*"
ros-noetic-desktop-full = ">=1.5.0,<2"
catkin_tools = ">=0.9.4,<0.10"
pyserial = ">=3.5,<4"


#[pypi-dependencies]
#pyarmor = "~=9.0.8"